### ISSUE TITLE
Couldn`t find package libboost-all-dev .

### ISSUE THREAD

**Issue by camellieeee** [CyberMiles/lity#1]
<img width="491" alt="err" src="https://user-images.githubusercontent.com/18331008/46092566-b8647e80-c1e7-11e8-84ff-99d4c5ba8243.png">
Found a problem when installing Lity.

**Comment by camellieeee** [comment]
run `sudo apt-get update `and then it worked

**Comment by camellieeee** [comment]
Only run on ubuntu ?

**Comment by hydai** [comment]
In the documentation, we only mention the build from source manual for ubuntu.

Actually, you can build lity on Mac OS, centos, and other *nix system.
And we have a one-liner script to install the external dependencies:

```
./scripts/install_deps.sh
```

I'll append this information in the build from source section later.

**Comment by hydai** [comment]
Hi @camellieeee. I've updated the manual.
https://lity.readthedocs.io/en/latest/download.html

**Comment by camellieeee** [comment]
@hydai Ok, thanks
