### ISSUE TITLE
Question: Where I can find some docs about `main()` or hello, world?

### ISSUE THREAD

**Issue by ghost** [CyberMiles/lity#22]
@redsquirrel 

Where I can find some docs about `main()` or hello, world?

**Comment by hydai** [comment]
Lity is based on Solidity v0.5.0, but adding some special language features for CyberMiles Virtual Machine including `safeuint` keyword, drools rule's engine grammar, and ethereum native interface support, etc.

So you may need to check both solidity v0.5.0 document (https://solidity.readthedocs.io/en/v0.5.0/introduction-to-smart-contracts.html) and our lity v1.2.7 document(https://lity.readthedocs.io/en/latest/index.html).
