### ISSUE TITLE
Where can I find a description of all the functions of the “personal”?

### ISSUE THREAD

**Issue by Msicyness** [CyberMiles/lity#3]
Like personal.newAccount, personal.lockAccount, personal.unlockAccount.

**Comment by tpmccallum** [comment]
Quick answer, if you are in the console and want to remember which functions are available, you can type personal followed by a period like this
```
personal. 
```
and then just hit the tab key on your keyboard a couple of times (quickly). This will output the functions which are available, as shown below.

```
> personal.
personal._requestManager personal.ecRecover       personal.importRawKey    personal.lockAccount     personal.sign            
personal.constructor     personal.getListAccounts personal.listAccounts    personal.newAccount      personal.unlockAccount   
personal.deriveAccount   personal.getListWallets  personal.listWallets     personal.sendTransaction 
```
**Descriptions**
As far as **description of all the functions**, these are available (with examples of syntax) at https://web3py.readthedocs.io/en/stable/web3.personal.html
