### ISSUE TITLE
Test chain synchronization timed out, what should I do?

### ISSUE THREAD

**Issue by Msicyness** [CyberMiles/lity#4]
![qq20181012-0](https://user-images.githubusercontent.com/41465470/46844832-355c3e80-ce0b-11e8-9d0c-e36eca33cd0b.png)

**Comment by tpmccallum** [comment]
Could you provide some information about how you installed the testnet please?
i.e. did you use this script < https://github.com/CyberMiles/travis/blob/develop/README.md#script >

Just curious because I would like to know what version of the testnet code and testnet config you are using.

Thanks
