### ISSUE TITLE
I found an error when running the code, how to solve it ? thank you.

### ISSUE THREAD

**Issue by xxlunch** [CyberMiles/lity#5]
code: source ./scripts/install_deps.sh
error: 
![2018-10-15 3 14 05](https://user-images.githubusercontent.com/44078281/46935175-fe955b00-d08c-11e8-9075-a1a375038ffb.png)
environment： macOS Mojave 10.14

**Comment by hydai** [comment]
Hi @xxlunch,

What is your version of mac os?

**Comment by hydai** [comment]
Oh. I got it. We have not tested on macOS Mojave 10.14.

**Comment by xxlunch** [comment]
Do you have any idea to help me run it on macOD.Mojave ?

**Comment by xxlunch** [comment]
Do you have any idea to help me run it on macOS.Mojave ? @hydai

**Comment by hydai** [comment]
Yes, you can paste these following lines after https://github.com/CyberMiles/lity/blob/lity/scripts/install_deps.sh#L87-L89 

```
            10.14)
                echo "Installing solidity dependencies on macOS 10.14 Mojave."
                ;;
```

The dependencies should be the same as High Sierra.

**Comment by xxlunch** [comment]
Thanks, I try to use it late.
