### ISSUE TITLE
This service crashed when I ran 'personal.unlockAccount' multiple times.

### ISSUE THREAD

**Issue by xxlunch** [CyberMiles/lity#6]
I think the cause of this problem is insufficient memory, but I have allocated 2G memory.
environment ： Linux on windows with Oracle VM VirtualBox
![Uploading QQ20181015-0.png…]()

**Comment by xxlunch** [comment]
![qq20181015-0](https://user-images.githubusercontent.com/44078281/46943869-34453e80-d0a3-11e8-8abf-5e21adb6e394.png)

**Comment by hydai** [comment]
Hi @xxlunch,

`personal.unlockAccount` is not a feature of lity but a built-in component of travis. Please forward your issue to travis (https://github.com/CyberMiles/travis/issues). Thanks.

**Comment by xxlunch** [comment]
ok ，thanks
