### ISSUE TITLE
Hello！The main network synchronization data is slow,and what should I do?

### ISSUE THREAD

**Issue by xxlunch** [CyberMiles/lity#8]
![126098a3fd6fabf072b3982a24861976](https://user-images.githubusercontent.com/44078281/47193789-57177180-d387-11e8-8ee9-cb2cf4d3985c.png)

**Comment by xxlunch** [comment]
Io network cpu occupancy is very low, resources are not consumed, but the synchronization is relatively slow, what parameters can be set?

**Comment by hydai** [comment]
This is a Travis issue.

Lity, the smart contract compiler, translates Lity smart contracts to the bytecodes for CyberMiles Virtual Machine.

If you have any question related to chain, please report to [Travis Issue](https://github.com/CyberMiles/travis) directly.
